import type { NextPage } from "next";
import Head from "next/head";
import { CnnModule } from "../modules/cnnmodule/CNNModule";

const Cnnmodule = () => {
  return (
    <div className="">
      <Head>
        <title> Inscripta | CNN-News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <CnnModule />
    </div>
  );
};
export default Cnnmodule;
