import Head from "next/head";
import LoginModule from "../modules/LoginModule/LoginModule";

const Login = () => {
  return (
    <div>
      <Head>
        <title> Inscripta | log in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <LoginModule />
    </div>
  );
};
export default Login;
