import type { NextPage } from "next";
import Head from "next/head";
import { NYTModule } from "../modules/nytmodule/NYTNews";

const Nytmodule = () => {
  return (
    <div className="">
      <Head>
        <title> Inscripta | News-api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <NYTModule />
    </div>
  );
};

export default Nytmodule;
